# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: a9ce26ed9eac81fa273b36b11d7c33e04b206eb5b32f1a6f8e74696157ae176d61cfafc41ac7759d5c718ac6a812cc82069c6474dc5a54efd53a542b7ca31ca5
  mailgun_api_key: key-7f9cce7561756e23e13f21764a19e671
  mailgun_domain: sandbox9ca6700b5798428d8e539e696978f873.mailgun.org

test:
  domain_name: example.com
  secret_key_base: 9784f8de19139a6ebc134b7f998300e8bf169315ec8e1e79cda0c49748a2308dc5be202b42b0358c79943b556c1c546f6fd60b13eea010181489ccd196fd8814

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailgun_api_key: <%= ENV["MAILGUN_API_KEY"] %>
  mailgun_domain: <%= ENV["MAILGUN_DOMAIN"] %>
